# setup.py
import argparse
import json
from pathlib import Path
from getpass import getpass

from multiversx_sdk import Account


TEMPLATE = '''# autogenerated .env
NETWORK={network}
PROXY_URL={proxy}
PRIVATE_KEY_PEM={pem_path}
POOL_MAP='{pool_map}'
'''


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--pem', help='Path to existing PEM. If omitted and --generate-pem not set, you must create a PEM yourself.')
    p.add_argument('--generate-pem', action='store_true', help='Generate a new wallet.pem in cwd (requires multiversx-sdk installed).')
    p.add_argument('--pool-map', default='{}', help='JSON map symbol->pair address (optional)')
    p.add_argument('--network', choices=['testnet','mainnet'], default='testnet')
    args = p.parse_args()


    pem_path = args.pem or ''

    from multiversx_sdk.wallet.user_keys import UserSecretKey

    if args.generate_pem:
        sk = UserSecretKey.generate()
        acct = Account(sk, hrp="erd")
        pem_path = "wallet.pem"
        acct.save_to_pem(Path(pem_path))
        print("Generated wallet PEM ->", pem_path)
    

    proxy = 'https://testnet-gateway.multiversx.com' if args.network == 'testnet' else 'https://gateway.multiversx.com'


    # validate pool_map
    try:
        _ = json.loads(args.pool_map)
    except Exception as e:
        print('Invalid pool-map JSON:', e)
        raise SystemExit(1)


    content = TEMPLATE.format(network=args.network, proxy=proxy, pem_path=pem_path, pool_map=args.pool_map)
    Path('.env').write_text(content)
    print('Wrote .env (NETWORK=%s, PROXY=%s, PEM=%s)' % (args.network, proxy, pem_path))
    print('Protect .env. If you generated wallet.pem, fund it from testnet faucet before trading.')


if __name__ == '__main__':
    main()